services:
  app:
    image: sitdh/pyhello
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9000:5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
    command: flask --app hello run --host 0.0.0.0 --port 5000
